name: Integración continua

on: [pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: npm run build

      - name: Ejecutar tests
        run: npm run test

      - name: Ejecutar ESLint
        run: npm run lint

  containerization:
    needs: integration
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
          file: ./Dockerfile
  feedback:
    needs: [integration, containerization]  # Este job depende de los dos anteriores
    runs-on: ubuntu-latest
    
    steps:
      - name: Notificación Slack - Build completada
        uses: Ilshidur/action-slack@v2
        if: success()  # Solo si la build fue exitosa
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "La build y los tests fueron completados exitosamente."

      - name: Notificación Slack - Error en la build
        uses: Ilshidur/action-slack@v2
        if: failure()  # Solo si hubo un error en la build
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "¡Hubo un error en la build! Revisa los logs."

      - name: Notificación Slack - Docker Build completada
        uses: Ilshidur/action-slack@v2
        if: success()  # Solo si la construcción del contenedor fue exitosa
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "La build del contenedor fue completada exitosamente."

      - name: Notificación Slack - Error en Docker Build
        uses: Ilshidur/action-slack@v2
        if: failure()  # Solo si hubo un error en la construcción del contenedor
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "¡Hubo un error al construir el contenedor! Revisa los logs."
